### ISSUE TITLE
Recuperacion de password

### ISSUE THREAD

**Issue by VGasull** [saezfernando/CalidadULP#13]
Swift_TransportException
Al solicitar link de recuperación de pasword

**Comment by saezfernando** [comment]
Me falto decirte que tenes que configurar tu archivo de entorno (.env) con los datos para el mail.
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME= **aca tu cuenta de gmail**
MAIL_PASSWORD=** aca el password de tu email **
MAIL_ENCRYPTION=ssl
Si todo funciona bien lo cerramos
