### ISSUE TITLE
Formulario Usuario

### ISSUE THREAD

**Issue by VGasull** [saezfernando/CalidadULP#3]
Formato campo dni y numero de teléfono numérico
Cambiar el orden de los componentes para asignar rol o aclarar

**Comment by saezfernando** [comment]
dni y telefono cambiados, el orden de los select no los cambie, porque eso lo implementa la libreria de javascript multi.select, pero en cambio le puse unos headers (Items a seleccionar, items seleccionados) Si les parece bien lo cerramos
