### ISSUE TITLE
Nuevo rol

### ISSUE THREAD

**Issue by VGasull** [saezfernando/CalidadULP#5]
Slug transformar en interno o sugerir autollenado con el nombre de rol
Cambiar Mensaje de error : campo level obligatorio por nivel obliatorio

**Comment by saezfernando** [comment]
Lo del campo slug quedo listo, lo del cartelito de level queda pendiente ya que el validador lanza el mensaje  automaticamente usando el nombre del campo (Y no puedo cambiar el nombre del campo a nivel porque la libreria roles lo usa con level)

**Comment by saezfernando** [comment]
Todo lo que tenga que ver con sintaxis del cartel se puede actualizar directamente en los archivos de la carpeta resources/lang/es y luego hacer el push para actualizarlo en el servidor

**Comment by saezfernando** [comment]
se cambio el cartel de Level a Nivel
