### ISSUE TITLE
Notificaciones

### ISSUE THREAD

**Issue by VGasull** [saezfernando/CalidadULP#8]
Cuando se agrega una notificación, sale un cartel aquí #3 
Si en la notificación se cambia el tipo a roles da una excepción, habría que ver que se hace con el campo destinatario
ErrorException in NotificationController.php line 81:
Invalid argument supplied for foreach()

**Comment by VGasull** [comment]
FatalErrorException in Model.php line 956:

**Comment by saezfernando** [comment]
listo. Se agregaron las validaciones en js
